name: generate page

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: install markdown
        run: pip install markdown
        

      - name: generate page
        run: python page_gen.py
        
      - name: commit page
        run: |
          git commit index.html -m "Re-build page" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
